
install:
	if [ ! -d "/usr/local/bin" ]; then mkdir -p "/usr/local/bin"; fi
#
	cp -f bin/delete /usr/local/bin/
	chmod +x /usr/local/bin/delete
update:
	cp -f bin/delete /usr/local/bin/
	chmod +x /usr/local/bin/delete

uninstall:
	rm -f  /usr/local/bin/delete

